import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("../../..", import.meta.url));
const SITE = join(ROOT, "site/index.html");
const WORKFLOW = join(ROOT, ".github/workflows/pages.yml");

test("GitHub Pages demo is a fixture, not a live daemon", () => {
  const html = readFileSync(SITE, "utf8");
  const workflow = readFileSync(WORKFLOW, "utf8");
  assert.match(html, /Interactive preview — no model calls/);
  assert.match(html, /@infra/);
  assert.match(html, /@pm/);
  assert.match(html, /@rd/);
  assert.match(html, /@design/);
  assert.match(html, /@marketing/);
  assert.match(html, /@handle → chatReply → HarnessService\.turn → runAgentLoop/);
  assert.match(html, /Ship it:/);
  assert.match(html, /pnpm i/);
  assert.match(html, /pnpm test/);
  assert.match(html, /pnpm dev/);
  assert.match(html, /npx @kevin5251984\/guild web/);
  assert.match(html, /Node ≥ 22\.19/);
  assert.match(html, /http:\/\/127\.0\.0\.1:7420/);
  assert.match(html, /<link rel="canonical" href="https:\/\/jakevin\.github\.io\/guild\/"/);
  assert.match(html, /property="og:title"/);
  assert.match(html, /property="og:url"/);
  assert.match(html, /name="twitter:card" content="summary"/);
  assert.match(html, /name="theme-color" content="#0B0E12"/);
  assert.match(html, /application\/ld\+json/);
  assert.match(html, /"@type": "SoftwareApplication"/);
  assert.doesNotMatch(html, /property="og:image"/);
  assert.doesNotMatch(html, /name="twitter:site"/);
  assert.doesNotMatch(html, /twitter:creator/);
  assert.match(html, /full_access/);
  assert.doesNotMatch(html, /\bfetch\s*\(/);
  assert.doesNotMatch(html, /XMLHttpRequest/);
  assert.doesNotMatch(html, /WebSocket/);
  assert.doesNotMatch(html, /127\.0\.0\.1:7420\/(channels|bots|workspace)/);
  assert.match(html, /not a task board/i);
  assert.match(html, /not a tavern/i);
  assert.doesNotMatch(html, /Quest board/);
  assert.match(html, /family=Cinzel/);
  assert.match(html, /family=Pixelify\+Sans/);
  assert.doesNotMatch(html, /family=Syne/);
  assert.match(html, /h1 \{[\s\S]*?font-family:\s*"Pixelify Sans"/);
  assert.match(html, /h2 \{[\s\S]*?font-family:\s*"Pixelify Sans"/);
  assert.match(html, /\.sign \{[\s\S]*?font-family:\s*Cinzel/);
  assert.doesNotMatch(html, /h1 \{[^}]*font-family:\s*Syne/);
  assert.doesNotMatch(html, /h2 \{[^}]*font-family:\s*Syne/);
  assert.match(html, /docs\/demo-hall-en-2026-08-31\.gif/);
  assert.doesNotMatch(html, /docs\/demo-hall-en-2026-08-29\.gif/);
  assert.match(workflow, /path: site/);
  assert.match(workflow, /actions\/deploy-pages/);
});

test("first-mention starts with wiring a model", () => {
  const first = readFileSync(join(ROOT, "docs/first-mention.md"), "utf8");
  const zh = readFileSync(join(ROOT, "docs/first-mention.zh.md"), "utf8");
  assert.match(first, /## 1\. Get a model \(do this first\)/);
  assert.match(first, /Guild is not usable/);
  assert.match(zh, /## 1\. 先接一個模型/);
  assert.match(zh, /Guild 不能用/);
  assert.doesNotMatch(first, /they can ack; they cannot think/);
  assert.doesNotMatch(zh, /冒險者還能回一聲/);
});

test("README points at the Pages demo without moving the first screen", () => {
  const en = readFileSync(join(ROOT, "README.md"), "utf8");
  const zh = readFileSync(join(ROOT, "README.zh.md"), "utf8");
  const ja = readFileSync(join(ROOT, "README.ja.md"), "utf8");
  const first = en.split("\n").slice(0, 20).join("\n");
  assert.match(first, /docs\/demo-hall-en-2026-08-31\.gif/);
  assert.match(first, /## Open the hall/);
  assert.doesNotMatch(first, /jakevin\.github\.io/);
  assert.match(first, /npx @kevin5251984\/guild web/);
  assert.doesNotMatch(first, /pnpm i/);
  assert.match(en, /npx @kevin5251984\/guild web/);
  assert.match(zh, /npx @kevin5251984\/guild web/);
  assert.match(ja, /npx @kevin5251984\/guild web/);
  for (const body of [en, zh, ja]) {
    assert.match(body, /https:\/\/jakevin\.github\.io\/guild\//);
    assert.match(body, /docs\/demo-hall-en-2026-08-31\.gif/);
    assert.match(body, /docs\/readme-hall-2026-08-29\.png/);
  }
});

test("Pages fixture switches zh-CN / zh-TW / en / ja in the DOM", () => {
  const html = readFileSync(SITE, "utf8");
  assert.match(html, /data-locale="zh-CN"/);
  assert.match(html, /data-locale="zh-TW"/);
  assert.match(html, /data-locale="en"/);
  assert.match(html, /data-locale="ja"/);
  assert.match(html, /aria-label="简体中文">简</);
  assert.match(html, /aria-label="繁體中文">繁</);
  assert.match(html, /aria-label="English">EN</);
  assert.match(html, /aria-label="日本語">日</);
  assert.match(html, /guild-pages-locale/);
  assert.match(html, /navigator\.language/);
  assert.match(html, /function detectLocale/);
  assert.match(html, /function setLocale/);
  assert.match(html, /document\.documentElement\.lang/);
  assert.match(html, /"seat\.infra": "基建"/);
  assert.match(html, /"seat\.pm": "專案經理"/);
  assert.match(html, /"seat\.rd": "研發"/);
  assert.match(html, /"seat\.design": "美術設計"/);
  assert.match(html, /"seat\.marketing": "行銷"/);
  assert.match(html, /html\[lang\^="zh"\] h1/);
  assert.match(html, /PingFang/);
  assert.match(html, /Hiragino/);
  assert.match(html, /class="skip" href="#try"/);
  assert.doesNotMatch(html, /<select/);
  assert.doesNotMatch(html, /🏳️|🇨🇳|🇹🇼|🇯🇵|🇺🇸/);
  const banners = [...html.matchAll(/"banner\.title": "([^"]+)"/g)].map((m) => m[1]);
  assert.equal(banners.length, 4);
  assert.ok(banners.every((s) => s === "Interactive preview — no model calls."));
  assert.match(html, /"pm\.after": "Ship it:/);
  assert.match(html, /"zh-TW": \{/);
  assert.match(html, /"zh-CN": \{/);
  assert.match(html, /\bnpx @kevin5251984\/guild web\b/);
});
